apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  name: gitlab-ce
spec:
  label:
    name: GitLab CE
    description: GitLab Community Edition
  distroID: dzinsou/gitlab-ce
  version: 14.10.0-ce.0
  configSchemaVersion: 8
  services:
  - id: gitlab
    label:
      name: GitLab
    endpoint:
      port: 80
      urlScheme: http
      isDashboard: true
  roles:
  - id: gitlab
    cardinality: "1"
    imageRepoTag: gitlab/gitlab-ce:14.10.0-ce.0
  config:
    selectedRoles:
    - gitlab
    roleServices:
    - roleID: gitlab
      serviceIDs:
      - gitlab
  systemdRequired: false