apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "python3-cpu-runner"
#  namespace: "" # Provide namespace if running from Ezmeral UI
  labels: 
    description: "python3-cpu-runner"
spec: 
  app: "gitlab-runner"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections: 
    secrets: 
      - hpecp-ext-auth-secret
#    clusters:
#      - gitlab-ce # Uncomment this line only if GitLab KD cluster is in the same tenant and is name gitlab-ce
  roles: 
    - 
      id: "gitlab-runner"
      members: 1
      serviceAccountName: "ecp-tenant-member-sa"
      resources: 
        requests: 
          cpu: "1"
          memory: "4Gi"
          nvidia.com/gpu: "0"
        limits: 
          cpu: "2"
          memory: "10Gi"
          nvidia.com/gpu: "0"
      env:
        - name: CI_SERVER_URL
          value: XXXXXXXXXX # Provide Gitlab URL here http://gitlab.example.com
        - name: REGISTRATION_TOKEN
          value: XXXXXXXXXX # Provide Gitlab token here