apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata: 
  name: "gitlab-ce"
#  namespace: "" # Provide namespace if running from Ezmeral UI
  labels: 
    description: "gitlab-ce"
spec: 
  app: "gitlab-ce"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections: 
    secrets: 
      - hpecp-ext-auth-secret
  roles: 
    - 
      id: "gitlab"
      members: 1
      serviceAccountName: "ecp-tenant-member-sa"
      resources: 
        requests: 
          cpu: "1"
          memory: "4Gi"
        limits: 
          cpu: "2"
          memory: "12Gi"
      env:
        - name: GITLAB_ROOT_PASSWORD
          value: ezmeral123
        - name: GITLAB_OMNIBUS_CONFIG
          value: gitlab_rails['initial_shared_runners_registration_token'] = "ezmeral123"